### ISSUE TITLE
No stats data fetched with Leaf2MQTT

### ISSUE THREAD

**Issue by hmfssantos** [kamiKAC/leaf2mqtt#19]
**Describe the bug**
During the regular fetch operation to retrieve the data from NissanConnect, there are no values for the Stats (Daily and Monthly).
I'm using V0.0.3, having started only a couple of days ago to use this code.
However, when I publish the command through the MQTT integration "leaf/command/stats/daily" with payload "update" I receive the desired string of data.

**LEAF_TYPE**
newerThanMay2019

**Expected behavior**
Include the string for the stats together with the rest of data (cockpit, climate, battery and location)

**Comment by kamiKAC** [comment]
Hi
Looking in the code [here](https://github.com/kamiKAC/leaf2mqtt/blob/1c15deedb63ee09656992f8301052041da2ffd92/src/leaf_2_mqtt.dart#L270-L280) shows that MQTT `update` message in topic `leaf/{vin}/command` fetches:
- Battery Status,
- Climate Status,
- Location,
- Cockpit Status
in above order.
Since Climate and Locations are currently not supported by API which seems to break execution of update resulting Cockpit Status is not updated.
I've comitted [experimental fix on branch](https://github.com/kamiKAC/leaf2mqtt/commit/6a7f68e406bbaf977df1e8fc4d0b399add5a7dd1) where not supported updates are moved to bottom so at least Cockpit status should be properly updated.
To update daily/monthly statistics please use topics `leaf/{vin}/stats/daily` and `leaf/{vin}/stats/monthly` respectively as mentioned documentation.

To check this fix use docker image `kamikac/leaf2mqtt:edge` (note that this is temporary tag). If this fix works for you please give some feedback so I will release it.

Best Regards
Marcin

**Comment by hmfssantos** [comment]
Some additional information. gathered from the log.
Subscribing to the stats/daily and stats/monthly, but not fetching+publishing the result for these:
 
FINE: 2024-05-28 11:50:53.784295: MqttClientWrapper: Subscribing to SJNFAAZE1U0123456/command
FINE: 2024-05-28 11:50:53.784421: MqttClientWrapper: Subscribing to command
FINE: 2024-05-28 11:50:53.784461: MqttClientWrapper: Subscribing to SJNFAAZE1U0123456/command/battery
FINE: 2024-05-28 11:50:53.784485: MqttClientWrapper: Subscribing to command/battery
FINE: 2024-05-28 11:50:53.784523: MqttClientWrapper: Subscribing to SJNFAAZE1U0123456/command/climate
FINE: 2024-05-28 11:50:53.784571: MqttClientWrapper: Subscribing to command/climate
**FINE: 2024-05-28 11:50:53.784612: MqttClientWrapper: Subscribing to SJNFAAZE1U0123456/command/stats/daily
FINE: 2024-05-28 11:50:53.784641: MqttClientWrapper: Subscribing to command/stats/daily
FINE: 2024-05-28 11:50:53.784663: MqttClientWrapper: Subscribing to SJNFAAZE1U0123456/command/stats/monthly
FINE: 2024-05-28 11:50:53.784700: MqttClientWrapper: Subscribing to command/stats/monthly**
FINE: 2024-05-28 11:50:53.784728: MqttClientWrapper: Subscribing to SJNFAAZE1U0123456/command/location
FINE: 2024-05-28 11:50:53.784750: MqttClientWrapper: Subscribing to command/location
FINE: 2024-05-28 11:50:53.784791: MqttClientWrapper: Subscribing to SJNFAAZE1U0123456/command/cockpitStatus
FINE: 2024-05-28 11:50:53.784817: MqttClientWrapper: Subscribing to command/cockpitStatus
FINER: 2024-05-28 11:50:53.784840: main: fetchAndPublishAllStatus for SJNFAAZE1U0123456

FINER: 2024-05-28 11:50:53.784905: main: fetchAndPublishBatteryStatus for SJNFAAZE1U0123456
FINEST: 2024-05-28 11:50:53.784962: LeafSession: Executing
FINER: 2024-05-28 11:50:53.785807: main: fetchAndPublishClimateStatus for SJNFAAZE1U0123456
FINEST: 2024-05-28 11:50:53.785890: LeafSession: Executing

FINER: 2024-05-28 11:50:53.787109: main: fetchAndPublishLocation for SJNFAAZE1U0123456
FINEST: 2024-05-28 11:50:53.787201: LeafSession: Executing
FINER: 2024-05-28 11:50:53.787894: main: fetchAndPublishCockpit for SJNFAAZE1U0123456
FINEST: 2024-05-28 11:50:53.787985: LeafSession: Executing

**Comment by kamiKAC** [comment]
Hi
Why not publish MQTT payloads periodically or on status update using HA?
`leaf/command/stats/daily` `update`
`leaf/command/stats/monthly` `update`

**Comment by hmfssantos** [comment]
Hello Marcin

Time is always short and sometimes a quick solution is the best solution.
I tried your advise and it works like a charm! 💯
Thanks for the sharing the idea.
